env:
  node: true
  es6: true
  mocha: true
extends:
  - eslint:recommended
  - airbnb-base
parserOptions:
  sourceType: module
rules:
  max-len:
    - error
    - 160
    - 2
    - ignoreUrls: true
      ignoreComments: false
      ignoreRegExpLiterals: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
  no-restricted-syntax:
    - error
    - LabeledStatement
    - WithStatement
  arrow-body-style:
    - error
    - always
